// Code generated by nero, DO NOT EDIT.
package repository

// Collection is the name of the collection
const Collection = "products"

// Column is a Product column
type Column int

// String implements Stringer
func (c Column) String() string {
	switch c {
	case ColumnID:
		return "id"
	case ColumnName:
		return "name"
	case ColumnCreatedAt:
		return "created_at"
	case ColumnUpdatedAt:
		return "updated_at"
	}

	return ""
}

const (
	ColumnID Column = iota
	ColumnName
	ColumnCreatedAt
	ColumnUpdatedAt
)
