// Code generated by nero, DO NOT EDIT.
package productrepo

// Table is the database table
const Table = "products"

// Field is a Product field
type Field int

// String returns the string representation of the field
func (f Field) String() string {
	return [...]string{
		"invalid",
		"id",
		"name",
		"created_at",
		"updated_at",
	}[f]
}

const (
	FieldID Field = iota + 1
	FieldName
	FieldCreatedAt
	FieldUpdatedAt
)
