// Code generated by nero, DO NOT EDIT.
package productrepo

// Collection is the name of the collection
const Collection = "products"

// Column is a Product column
type Column int

// String returns the string representation of the Column
func (c Column) String() string {
	return [...]string{
		"id",
		"name",
		"created_at",
		"updated_at",
	}[c]
}

const (
	ColumnID Column = iota
	ColumnName
	ColumnCreatedAt
	ColumnUpdatedAt
)
